# Generated by Django 3.2 on 2023-02-20 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='captain_commune',
            new_name='CaptainCommune',
        ),
        migrations.RenameModel(
            old_name='Historicalcaptain_commune',
            new_name='HistoricalCaptainCommune',
        ),
        migrations.RenameModel(
            old_name='Historicalleader_resp_neighborhoods',
            new_name='HistoricalLeaderRespNeighborhoods',
        ),
        migrations.RenameModel(
            old_name='Historicalpolling_stations',
            new_name='HistoricalPollingStations',
        ),
        migrations.RenameModel(
            old_name='Historicalvoter_data',
            new_name='HistoricalVoterData',
        ),
        migrations.RenameModel(
            old_name='leader_resp_neighborhoods',
            new_name='LeaderRespNeighborhoods',
        ),
        migrations.RenameModel(
            old_name='polling_stations',
            new_name='PollingStations',
        ),
        migrations.RenameModel(
            old_name='voter_data',
            new_name='VoterData',
        ),
    ]
