# Generated by Django 3.2 on 2023-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0003_auto_20230221_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmunicipality',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
