# Generated by Django 3.2 on 2023-02-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0004_auto_20230221_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captains',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalcaptains',
            old_name='names',
            new_name='name',
        ),
    ]
