# Generated by Django 3.2 on 2023-02-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0006_auto_20230222_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalleader',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='names',
            new_name='name',
        ),
    ]
