# Generated by Django 3.2 on 2023-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0008_auto_20230222_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmunicipality',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
